version: '3.4'

services:

  postgres:
    container_name: auth-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    volumes:
      - ./database/_postgres_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: auth-api
    image: maven:3.6-jdk-10-slim
    volumes:
      - ../api/:/usr/src/app
      - $HOME/.m2:/root/.m2
    working_dir: /usr/src/app
    command: mvn spring-boot:run
    ports:
      - "9000:9000"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"

  frontend:
    container_name: auth-ui
    image: node:10.11.0
    volumes:
      - ../ui/:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"