version: '3.1'

services:
  postgres:
    container_name: postgres-auth
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    ports:
      - "5436:5432"
    volumes:
    - ./_postgres:/var/lib/postgresql/data
