version: '3.1'

services:

  postgres-local:
    container_name: auth-postgres-local
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
    - ./_postgres:/var/lib/postgresql/data